EMOJI_DICT = {
    "😀": " vui ",
    "😃": " vui ",
    "😄": " vui ",
    "😁": " vui ",
    "😊": " vui ",
    "🙂": " vui ",
    "😂": " cười ",
    "🤣": " cười ",
    "😍": " yêu_thích ",
    "🥰": " yêu_thích ",
    "😘": " yêu_thích ",
    "❤️": " yêu_thích ",
    "❤": " yêu_thích ",
    "👍": " tốt ",
    "👏": " khen ",
    "🙏": " cảm_ơn ",
    "😢": " buồn ",
    "😭": " buồn ",
    "😞": " thất_vọng ",
    "😡": " tức_giận ",
    "😠": " tức_giận ",
    "👎": " tệ ",
}